config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "welcome#home"

  # custom actions for the welcome controller
  get "/home" => "welcome#home"
  get "/preview" => "welcome#preview"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users do
    get "/change_password" => "users#change_password"
  end
  resources :clients, only: [:new, :create, :index, :update, :destroy]

  resources :categories
  resources :info_requests do
    resources :submissions, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :submissions, only: [:index]
  resources :relationships, only: [:create, :destroy]

  resources :teams
  resources :team_memberships

  resources :client_requests, only: [:index]
  resources :client_submissions, only: [:index]
  resources :consultant_requests, only: [:index]
  resources :consultant_submissions, only: [:index]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :info_requests, only: [:index, :show] do
        resources :submissions, only: [] do
          post :update, on: :collection
        end
      end
    end
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:index] do
        post "sign_in" => "users#sign_in", on: :collection
        delete "sign_out" => "users#sign_out", on: :collection
      end
      resources :submissions, only: [:index, :create]
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user
  helper_method :mailbox, :conversation, :recipient_names

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all

    conversation = current_user.
      send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation_path(conversation)
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def recipient_names(conversation)
    conversation.recipients.map do |recipient|
      "#{recipient.first_name} #{recipient.last_name}"
    end.join(", ")
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= content_tag_for(:tr, conversation) do |conversation| %>
  <td><%= current_user.sender(conversation) %></td>
  <td><%= link_to conversation.subject, conversation_path(conversation), class: "green-link" %></td>
  <td><%= current_user.last_message_date(conversation) %></td>
  <td class="text-center" width="5%">
    <% if conversation.is_completely_trashed?(current_user) %>
      <%= link_to 'Untrash', untrash_conversation_path(conversation), method: :post %>
    <% else %>
      <%= link_to fa_icon("trash-o"), trash_conversation_path(conversation), method: :post, class: "trash-icon" %>
    <% end %>
  </td>
<% end %>

app/views/conversations/_form.html.erb
<%= simple_form_for :conversation, url: :conversations do |f| %>
  <%= f.input :recipients, hint: "Please enter recipients' emails, separated by commas." %>
  <%= f.input :subject %>
  <%= f.input :body, as: :text %>
  <div class="form-actions">
    <%= f.button :submit, 'Start Conversation', class: 'btn-primary' %>
    <%= f.button :submit, 'Cancel', type: :reset, class: 'btn-danger' %>
  </div>
<% end %>

app/views/conversations/index.html.erb
<% content_for :messenger do %>
  <% if params[:filter] == 'inbox' %>
    <h1>Inbox</h1>
    <table class="table table-bordered">
      <tbody><%= render collection: mailbox.inbox, partial: 'conversation' %></tbody>
    </table>
  <% elsif params[:filter] == 'sent' %>
    <h1>Sent Messages</h1>
    <table class="table table-bordered">
      <tbody><%= render collection: mailbox.sentbox, partial: 'conversation' %></tbody>
    </table>
  <% else %>
    <h1>Trash</h1>
    <table class="table table-bordered">
      <tbody><%= render collection: mailbox.trash, partial: 'conversation' %></tbody>
    </table>
  <% end %>
<% end %>

app/views/conversations/new.html.erb
<% content_for :messenger do %>
<h1>Start Conversation</h1>
<%= render 'form' %>
<% end %>

app/views/conversations/show.html.erb
<% content_for :messenger do %>
<h3><strong>Subject:</strong> <%= conversation.subject.titleize %></h3>
<%= content_tag_for(:div, conversation.receipts_for(current_user)) do |receipt| %>
  <% message = receipt.message %>
  <div class="row">
    <div class="col-sm-2"><%= message.sender.full_name %></div>
    <div class="col-sm-10"><%= message.body %></div>
  </div>
<% end %>

<hr>
<%= render 'messages/form', conversation: conversation %>
<% end %>