config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "welcome#home"

  # custom actions for the welcome controller
  get "/home" => "welcome#home"
  get "/preview" => "welcome#preview"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users do
    get "/change_password" => "users#change_password"
  end
  resources :clients, only: [:new, :create, :index, :update, :destroy]

  resources :categories
  resources :info_requests do
    resources :submissions, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :submissions, only: [:index]
  resources :relationships, only: [:create, :destroy]

  resources :teams
  resources :team_memberships

  resources :client_requests, only: [:index]
  resources :client_submissions, only: [:index]
  resources :consultant_requests, only: [:index]
  resources :consultant_submissions, only: [:index]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :info_requests, only: [:index, :show] do
        resources :submissions, only: [] do
          post :update, on: :collection
        end
      end
    end
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:index] do
        post "sign_in" => "users#sign_in", on: :collection
        delete "sign_out" => "users#sign_out", on: :collection
      end
      resources :submissions, only: [:index, :create]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  acts_as_messageable
  before_create :generate_api_key

  has_many :info_requests
  has_many :submissions

  has_many :relationships, dependent: :destroy
  has_many :clients, through: :relationships, source: :relation
  has_many :inverse_relationships, class_name: "Relationship", foreign_key: "relation_id"
  has_many :consultants, through: :inverse_relationships, source: :user

  has_many :team_memberships, dependent: :nullify
  has_many :teams, through: :team_memberships

  validates :password, presence: true, length: {minimum: 6}, on: :create
  validates :first_name, presence: true, on: :create
  validates :last_name, presence: true, on: :create
  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}".titleize
  end

  def mailboxer_email(object)
    email
  end

  def active_clients
    relationships.active_relationships
  end

  def archived_clients
    relationships.archived_relationships
  end

  def client_status(current_user)
    r = current_user.relationships.find_by_relation_id(self.id)
    r.aasm_state.titleize
  end

  def client_names
    clients.map do |client|
      client.full_name
    end
  end

  def consultant?
    role.downcase == "consultant" if role
  end

  def client?
    role.downcase == "client" if role
  end

  def info_requests
    if client?
      InfoRequest.includes(:relationship).where(relationships: {relation_id: self.id})
    else
      InfoRequest.where(user_id: self).order("created_at desc")
    end
  end

  def submissions
    if consultant?
      Submission.includes(:relationship).where(relationships: {user_id: self.id})
    else
      Submission.where(user_id: self).order(:id)
    end
  end

  def pending_requests_count
    info_requests.where(completed: false).count
  end

  def pending_submissions_count
    submissions.where(completed: false).count
  end

  def unread_conversations
    count = 0
    mailbox.inbox.each do |c|
      c.receipts_for(self).each do |r|
        if r.is_unread?
          count += 1
        end
      end
    end
    return count
  end

  def unread_messages(conversation)
    conversation.receipts_for(self).each do |r|
      if r.is_unread?
        count += 1
      end
    end
  end

  def sender(conversation)
    User.find(conversation.messages.first.sender_id).full_name
  end

  def last_message_date(conversation)
    conversation.messages.last.created_at.strftime("%D")
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  private

  def generate_api_key
    self.api_key = SecureRandom.hex(32)
    while User.exists?(api_key: self.api_key)
      self.api_key = SecureRandom.hex(32)
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::BaseController
  skip_before_action :verify_authenticity_token

  def index
    @users = User.all
    render json: {users: @users}
  end

  def sign_in
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      render json: @user
    else
      head :unauthorized
    end
  end

  def sign_out
    head :ok
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show, :edit, :update, :destroy]
  before_action :find_user, only: [:show, :edit, :update]

  def new
    @user = User.new
    if params[:consultant_id]
      @consultant = User.find params[:consultant_id]
      @consultant_id = @consultant.id
    else
      @consultant_id = nil
    end
    respond_to do |format|
      format.html { render :new } #for my controller, i wanted it to be JS only
      format.js   { :new }
    end
  end

  def create
    user = User.new user_params
    if user.save
      if params[:user][:consultant]
        Relationship.create(user_id: params[:user][:consultant].to_i, relation_id: user.id)
      end
      log_in(user)
      redirect_to info_requests_path, notice: "Profile created successfully!"
    else
      flash[:alert] = "User not created, see errors!"
      redirect_to new_user_path
    end
  end

  def show
    respond_to do |format|
      format.js   { :show }
      format.html { render :show }
    end
  end

  def index
  end

  def edit
    respond_to do |format|
      format.js {:edit}
      format.html {:edit}
    end
  end

  def update
    respond_to do |format|
      if @user.update user_params
        format.html { redirect_to user_path(@user), notice: "Profile updated successfully."}
        format.js   { render :update_success }
      else
        format.html { flash[:alert] = "Profile not updated."
                      @changing_password ? (render :change_password) : (render :edit) }
        format.js   { render :update_failure }
      end
    end
  end

  def destroy
    @user = User.find params[:id]
    if can? :destroy, @user
      @user.destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "User deleted!"
    else
      redirect_to root_path, notice: "User not deleted!"
    end
  end

  def change_password
    @user = User.find params[:user_id]
  end

  private

  def find_user
    @user = User.find current_user.id
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :role, :password)
  end

  def check_password
    authentic_password = @user.authenticate(params[:user]["current_password"])
    different_password = params[:user]["current_password"] != params[:user]["password"]
    @changing_password = params[:user]["password"]
    @changing_password ? (authentic_password && different_password) : authentic_password
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if user_signed_in? %>
<%= simple_form_for @user, remote: true do |f| %>
  <%= f.input_field :consultant, as: :hidden, value: @consultant_id %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :role, collection: ["Client", "Consultant"], :selected => (@user.consultant? ? "Consultant" : "Client") %>
  <%= f.input :email %>
  <%= f.submit class: "btn btn-primary" %>
  <%= link_to "Change Password", user_change_password_path(@user), class: "btn btn-info" %>
<% end %>

<% else %>
  <%= simple_form_for @user do |f| %>
    <%= f.input_field :consultant, as: :hidden, value: @consultant_id %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :role, collection: ["Client", "Consultant"], :selected => (@user.consultant? ? "Consultant" : "Client") %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.submit "Create Account", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/users/_profile.html.erb
<p><strong>First Name:</strong> <%= @user.first_name %></p>
<p><strong>Last Name:</strong> <%= @user.last_name %></p>
<p><strong>Email:</strong> <%= @user.email %></p>
<br>
<div class="row flexrow">
  <div class="col-sm-6"><%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-warning btn-sm", remote: true  %></div>
  <div class="col-sm-6 flexcol-prof"><%= link_to "Delete Account", user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete your account?"}, class: "text-danger" %></div>
</div>

app/views/users/change_password.html.erb
<% content_for :profile do %>
<h1>Change Password</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :current_password %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
<% end %>

app/views/users/edit.html.erb
<% content_for :profile do %>
<h1>Edit Profile</h1>

<%= render "form" %>
<% end %>

app/views/users/edit.js.erb
$("#profile").hide().html("<%= j render 'form' %>").fadeIn();

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form" %>

app/views/users/new.js.erb
var title       =   '.modal-title',
    loader      =   '.ajax-loader',
    content     =   '.modal-body-content',
    dataRemote  =   'a[data-remote=true]',
    toolbar     =   'div.modal-footer',
    modal       =   '#ajax-modal';

//i set the title through a helper function
$(title).html('Sign Up');
//hides the modal and shows the ajax content
$(loader).fadeToggle('fast', function() {
  $(loader).fadeOut('slow');
  $(content).html('<%= j render("form") %>');
  $(modal).modal();
});
//brings the loader back up + gets rid of the content when linking to another controller method etc
$(content).on('click', dataRemote, function(){
  $(content).fadeOut('slow', function() {
    $(content).empty();
    $(loader).fadeIn('slow');
  });
});

app/views/users/show.html.erb
<% content_for :profile do %>
<h1>Your Profile</h1>
<%= render "profile" %>
<% end %>

app/views/users/show.js.erb
var title       =   '.modal-title',
    loader      =   '.ajax-loader',
    content     =   '.modal-body-content',
    dataRemote  =   'a[data-remote=true]',
    toolbar     =   'div.modal-footer',
    modal       =   '#ajax-modal';

//i set the title through a helper function
$(title).html('View Profile');
//hides the modal and shows the ajax content
$(loader).fadeToggle('fast', function() {
  // $(loader).fadeOut('slow');
  $(content).html('<div id="profile"><%= j render("profile") %></div>');
  $(modal).modal();
});
//brings the loader back up + gets rid of the content when linking to another controller method etc
// $(content).on('click', dataRemote, function(){
//   $(content).fadeOut('slow', function() {
//     $(content).empty();
//     $(loader).fadeIn('slow');
//   });
// });

app/views/users/update_failure.js.erb
alert("Profile not updated!");

app/views/users/update_success.js.erb
$("#profile").hide().html("<%= j render 'profile' %>").fadeIn();