config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "welcome#home"

  # custom actions for the welcome controller
  get "/home" => "welcome#home"
  get "/preview" => "welcome#preview"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users do
    get "/change_password" => "users#change_password"
  end
  resources :clients, only: [:new, :create, :index, :update, :destroy]

  resources :categories
  resources :info_requests do
    resources :submissions, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :submissions, only: [:index]
  resources :relationships, only: [:create, :destroy]

  resources :teams
  resources :team_memberships

  resources :client_requests, only: [:index]
  resources :client_submissions, only: [:index]
  resources :consultant_requests, only: [:index]
  resources :consultant_submissions, only: [:index]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :info_requests, only: [:index, :show] do
        resources :submissions, only: [] do
          post :update, on: :collection
        end
      end
    end
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:index] do
        post "sign_in" => "users#sign_in", on: :collection
        delete "sign_out" => "users#sign_out", on: :collection
      end
      resources :submissions, only: [:index, :create]
    end
  end
end

app/models/info_request.rb
class InfoRequest < ActiveRecord::Base
  has_one :submission, dependent: :destroy
  belongs_to :category
  belongs_to :user
  belongs_to :relationship
  paginates_per 10

  # scope :scope_date, -> { order(created_at: :desc) }

  validates :title, presence: true
  validates :relationship_id, presence: true
  validates :category_id, presence: true

  def category_name
    Category.where(id: category_id)[0].name
  end

  def creator
    u = User.find user_id
    u.full_name
  end

  def client_name
    relationship = Relationship.find relationship_id
    relationship.client_name
  end

  def content
    {"Client": client_name,
      "Consultant": creator,
      "Category": category_name,
      "Description": description,
      "Requirements": requirements}
  end

  def priority_label
    case priority
    when 1
      "High"
    when 2
      "Medium"
    when 3
      "Low"
    end
  end

  def category_label
    case category_name
    when "Text"
      "Text"
    when "Image"
      "Image"
    when "Login"
      "Login"
    when "File"
      "File"
    end
  end
end

app/controllers/api/v1/info_requests_controller.rb
class Api::V1::InfoRequestsController < Api::BaseController
  def index
    user = User.find params[:user_id]
    @info_requests = user.info_requests
    render json: @info_requests
  end

  def show
    @info_request = InfoRequest.find params[:id]
    render json: @info_request
  end
end

app/controllers/info_requests_controller.rb
class InfoRequestsController < ApplicationController
  before_action :authenticate_user, only: [:show]
  before_action :find_info_request, only: [:show, :edit, :update]

  def new
    @info_request = InfoRequest.new
    respond_to do |format|
      format.js {:new}
    end
  end

  def create
    @info_request = InfoRequest.new info_request_params
    @info_request.user = current_user
    respond_to do |format|
      if @info_request.save
        client_id = Relationship.find(@info_request.relationship_id).relation_id
        InfoRequestsMailer.new_request(current_user.id, client_id, @info_request).deliver_later
        format.html { redirect_to info_requests_path, notice: "Request created!" }
        format.js   { render :create_success }
      else
        format.html { render :new, alert: "Request not created!" }
        format.js   { render :create_failure }
      end
    end
  end

  def index
    # TODO: Refactor this into model
    respond_to do |format|
      if params[:filter] == "false"
        @info_requests = current_user.info_requests.where(completed: "false").page(params[:page])
        format.html
        format.js   { render :filter_requests }
      elsif params[:filter] == "true"
        @info_requests = current_user.info_requests.where(completed: "true").page(params[:page])
        format.html
        format.js   { render :filter_requests }
      else
        @info_requests = current_user.info_requests.page(params[:page])
        format.html
        format.js   { render :filter_requests }
      end
    end
  end

  def show
    respond_to do |format|
      format.js {:show}
    end
  end

  def edit
    respond_to do |format|
      format.js   {:edit}
      format.html {:edit}
    end
  end

  def update
    respond_to do |format|
      if @info_request.update info_request_params
        format.html { redirect_to @info_request, notice: "Request updated!"}
        format.js   { render :update_success }
      else
        format.html { render :edit, alert: "Unable to update request. Please check errors."}
        format.js   { render :update_failure }
      end
    end
  end

  def destroy
    @info_request = current_user.info_requests.find params[:id]
    @info_request.destroy
    redirect_to info_requests_path, notice: "Request deleted!"
  end

  private

  def info_request_params
    params.require(:info_request).permit(:title, :description, :requirements, :category_id, :completed, :relationship_id, :priority)
  end

  def find_info_request
    @info_request = InfoRequest.find params[:id]
  end
end

app/helpers/api/v1/info_requests_helper.rb
module Api::V1::InfoRequestsHelper
end

app/helpers/info_requests_helper.rb
module InfoRequestsHelper
end

app/views/info_requests/_category.html.erb
<% if info_request.category_name == "Text" %>
<span class="label label-text">Text</span>
<% end %>
<% if info_request.category_name == "Image" %>
<span class="label label-image">Image</span>
<% end %>
<% if info_request.category_name == "File" %>
<span class="label label-file">File</span>
<% end %>
<% if info_request.category_name == "Login" %>
<span class="label label-login">Login</span>
<% end %>

app/views/info_requests/_info_request.html.erb
<div class="row flexrow show-header">
  <div class="col-sm-9">
    <h1>Info Request #<%= @info_request.id %>: <%= @info_request.title %></h1>
    <p>Priority: <%= @info_request.priority_label %></p>
  </div>
  <div class="col-sm-3 text-right flexcol-center">
    <div class="btn-group flexrow-center">
      <% if current_user.client? && @info_request.submission %>
        <%= link_to "Edit Submission", edit_info_request_submission_path(@info_request, @info_request.submission), class: "btn btn-warning btn-sm", "data-no-turbolink": true %>
      <% elsif current_user.client? %>
        <%= link_to "Create Submission", new_info_request_submission_path(@info_request), class: "btn btn-success btn-sm" %>
      <% else %>
        <%= link_to "Edit Request", edit_info_request_path(@info_request), class: "btn btn-warning btn-sm" %>
        <%= link_to "Delete Request", info_request_path(@info_request), method: :delete, data: {confirm: "Are you sure you want to delete this submission?"}, class: "btn btn-danger btn-sm" %>
      <% end %>
    </div>
  </div>
</div>
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Additional Information</h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <% @info_request.content.each do |key, value| %>
        <% if !value.empty? %>
          <dt><%= key %></dt>
          <dd><%= value %></dd>
        <% end %>
      <% end %>
    </dl>
  </div>
</div>

app/views/info_requests/_info_requests.html.erb
<h1>Requests</h1>
<% if @info_requests.length >= 1 %>
<div class="table-responsive">
  <table width="100%" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th width="25%">Title</th>
        <th class="text-center">Category</th>
        <th class="text-center">Created</th>
        <% if current_user.consultant? %>
          <th>Client</th>
        <% else %>
          <th>Consultant</th>
        <% end %>
        <th class="text-center">Actions</th>
        <th class="text-center">Completed</th>
      </tr>
    </thead>

    <tbody>
      <% @info_requests.each do |info_request| %>
        <tr>
          <td><%= info_request.title %></td>
          <td class="text-center"><span class="label label-<%= info_request.category_name.downcase %>"><%= info_request.category_label %></span></td>
          <td class="text-center"><%= info_request.created_at.strftime("%D")%></td>
          <% if current_user.consultant? %>
          <td><%= info_request.client_name %></td>
          <td class="text-center flexrow-center btn-group">
              <%= link_to "View", info_request_path(info_request), class: "btn btn-info btn-sm", remote: true %>
              <%= link_to "Edit", edit_info_request_path(info_request), class: "btn btn-warning btn-sm", remote: true %>
              <%= link_to "Delete", info_request_path(info_request), method: :delete, data: {confirm: "Are you sure you want to delete this submission?"}, class: "btn btn-danger btn-sm" %> </td>
          <% else %>
          <td><%= info_request.creator %></td>
          <td class="text-center flexrow-center btn-group">
            <%= link_to "View Request", info_request_path(info_request), class: "btn btn-info btn-sm", remote: true %>
              <% if info_request.submission %>
                <%= link_to "View Submission", info_request_submission_path(info_request, info_request.submission), class: "btn btn-success btn-sm" %> </td>
              <% else %>
                <%= link_to "Start Submission", new_info_request_submission_path(info_request), class: "btn btn-pink btn-sm", "data-no-turbolink": true  %> </td>
              <% end %>
          <% end %>
          <td class="text-center">
            <!-- <div id="<%#= dom_id(info_request) %>_completed" style="display:inline;"> -->
              <%#= render "toggle_completed", info_request: info_request %>
            <!-- </div> -->
            <% if info_request.completed %>
              <i class='material-icons'>check</i>
            <% else %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<h3>No Requests!</h3>
<% end %>


<div class="text-center"><%= paginate @info_requests, theme: 'bootstrap3' %></div>

app/views/info_requests/create_failure.js.erb
alert("Failed to create request, please see errors!");

app/views/info_requests/create_success.js.erb
$("#dash-content").hide().html("<%= j render 'info_request', info_request: @info_request %>").fadeIn();

app/views/info_requests/edit.js.erb
$("#dash-content").hide().html("<h1>Edit Request</h1><%= j render 'form', info_request: @info_request %>").fadeIn();

app/views/info_requests/filter_requests.js.erb
$("#dash-content").hide().html("<%= j render 'info_requests', info_requests: @info_requests %>").fadeIn();

app/views/info_requests/index.html.erb
<%= render "info_requests" %>

app/views/info_requests/new.html.erb
<h1>New Request</h1>
<%= render 'form' %>

app/views/info_requests/new.js.erb
$("#dash-content").hide().html("<h1>New Request</h1><%= j render 'form', info_request: @info_request %>").fadeIn();

app/views/info_requests/show.html.erb
<%= render 'info_request' %>

app/views/info_requests/show.js.erb
$("#dash-content").hide().html("<%= j render 'info_request', info_request: @info_request %>").fadeIn();

app/views/info_requests/update_failure.js.erb
alert("Unable to update request! Please check errors.");

app/views/info_requests/update_success.js.erb
$("#dash-content").hide().html("<%= j render 'info_request', info_request: @info_request %>").fadeIn();