config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "welcome#home"

  # custom actions for the welcome controller
  get "/home" => "welcome#home"
  get "/preview" => "welcome#preview"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :users do
    get "/change_password" => "users#change_password"
  end
  resources :clients, only: [:new, :create, :index, :update, :destroy]

  resources :categories
  resources :info_requests do
    resources :submissions, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :submissions, only: [:index]
  resources :relationships, only: [:create, :destroy]

  resources :teams
  resources :team_memberships

  resources :client_requests, only: [:index]
  resources :client_submissions, only: [:index]
  resources :consultant_requests, only: [:index]
  resources :consultant_submissions, only: [:index]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :info_requests, only: [:index, :show] do
        resources :submissions, only: [] do
          post :update, on: :collection
        end
      end
    end
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users, only: [:index] do
        post "sign_in" => "users#sign_in", on: :collection
        delete "sign_out" => "users#sign_out", on: :collection
      end
      resources :submissions, only: [:index, :create]
    end
  end
end

app/views/layouts/_ajax_modal.html.erb
<div class="modal fade" id="ajax-modal" tabindex="-1">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body">
      <div class="modal-body-content"></div>
      <div class="ajax-loader"></div>
    </div>
    <div class="modal-footer"></div>
  </div>
</div>

app/views/layouts/_dash_nav.html.erb
<ul class="list-group">
  <% if current_user.consultant? %>
    <li><%= link_to "New Request", new_info_request_path, class: "btn btn-primary", remote: true %></li>
    <li class="list-group-item"><%= link_to "All Requests", info_requests_path({filter: "all"}), remote: true %></li>
    <li class="list-group-item"><%= link_to "Completed Requests", info_requests_path({filter: "true"}), remote: true  %></li>
    <li class="list-group-item"><span class='badge'><%= current_user.pending_requests_count %></span><%= link_to "Pending Requests", info_requests_path({filter: "false"}), remote: true %></li>
    <hr>
    <li><%= link_to "Add New Client", new_client_path, class: "btn btn-primary", remote: true %></li>
    <li class="list-group-item"><%= link_to "All Clients", clients_path({filter: "all"}), remote: true %></li>
    <li class="list-group-item"><%= link_to "Active Clients", clients_path({filter: "active"}), remote: true %></li>
    <li class="list-group-item"><%= link_to "Archived Clients", clients_path({filter: "archive"}), remote: true %></li>
    <li class="list-group-item"><%= link_to "View Submissions", submissions_path, remote: true %></li>
  <% else %>
    <li class="list-group-item"><%= link_to "All Requests", info_requests_path({filter: "all"}), remote: true  %></li>
    <li class="list-group-item"><span class='badge'><%= current_user.pending_requests_count %></span><%= link_to "Pending Requests", info_requests_path({filter: "false"}), remote: true %></li>
    <li class="list-group-item"><%= link_to "All Submissions", submissions_path({filter: "all"}), remote: true  %></li>
    <li class="list-group-item"><span class='badge'><%= current_user.pending_submissions_count %></span><%= link_to "Pending Submissions", submissions_path({filter: "false"}), remote: true  %></li>
  <% end %>
  </ul>

app/views/layouts/_dash_nav_messenger.html.erb
<ul class="list-group">
  <li><%= link_to 'New Message', :new_conversation, class: "btn btn-primary" %></li>
  <li class="list-group-item"><span class='badge'><%= current_user.unread_conversations %></span><%= link_to "Inbox", conversations_path({filter: "inbox"}) %></li>
  <li class="list-group-item"><%= link_to "Sent", conversations_path({filter: "sent"}) %></li>
  <li class="list-group-item"><%= link_to "Trash", conversations_path({filter: "trash"}) %></li>
</ul>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; ZenJobs</p>
</footer>

app/views/layouts/_navbar.html.erb
<div class="row">
  <div class="col-sm-12 no-padding">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#zenjobs_nav" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("logo.png", height: "25px"), root_path, class: "navbar-brand", "data-no-turbolink": true%>
          <% if !user_signed_in? %>
          <ul class="nav navbar-nav navbar-left"><li><%= link_to "Take a look inside!", preview_path, "data-no-turbolink": true %></li></ul>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="zenjobs_nav">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <p class="navbar-text">Welcome <%= link_to current_user.full_name, user_path(current_user), data: { toggle: "modal", target: "#ajax-modal" }, remote: true  %>!</p>
              <li><%= link_to raw("<i class='material-icons'>apps</i>"), info_requests_path %></li>
              <!-- <li><%#= link_to raw("<i class='material-icons'>notifications</i>"), info_requests_path %></li> -->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class='material-icons'>notifications</i></a>
                <ul class="dropdown-menu">
                  <% if notifications? %>
                    <li><%= link_to raw("Pending Requests <span class='badge'>#{current_user.pending_requests_count}</span>"), info_requests_path({filter: "false"}) %></li>
                    <li><%= link_to raw("Pending Submissions <span class='badge'> #{current_user.pending_submissions_count}</span>"), submissions_path({filter: "false"})  %></li>
                    <li><%= link_to raw("New Messages <span class='badge'>#{current_user.unread_conversations}</span>"), conversations_path({filter: "inbox"}) %></li>
                  <% else %>
                    <li><p>No New Notifications!</p></li>
                  <% end %>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="material-icons">account_circle</i></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "View Profile", user_path(current_user), data: { toggle: "modal", target: "#ajax-modal" }, remote: true %></li>
                  <li><%= link_to 'My Conversations', conversations_path({filter: "inbox"}) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Log Out", sessions_path, method: :delete, data: {confirm: "Are you sure you want to log out?"} %></li>
                </ul>
              </li>
            <% else %>
              <li><div><%= link_to "Sign Up", new_user_path, data: { toggle: "modal", target: "#ajax-modal" }, remote: true, class: "btn btn-primary navbar-btn" %></div></li>
              <li><%= link_to "Sign In", new_session_path, data: { toggle: "modal", target: "#ajax-modal" }, remote: true %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
</div>

app/views/layouts/_notices.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= notice %>
</div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZenJobs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/ajax_modal' %>
<% if content_for? :home %>
  <div class="container-fluid flexcol">
    <div>
      <%= render 'layouts/navbar' %>
    </div>
  </div>
  <%= yield :home %>
  <%= render 'layouts/footer' %>
<% elsif content_for? :preview %>
  <div class="container-fluid flexcol">
    <div>
      <%= render 'layouts/navbar' %>
    </div>
    <%= yield :preview %>
  </div>
  <%= render 'layouts/footer' %>
<% else %>
  <div class="container-fluid flexcol">
    <div>
      <%= render 'layouts/navbar' %>
    </div>
    <% if user_signed_in? %>
    <% if content_for? :profile %>
      <div id="page-content" class="flexcol">
        <div class="col-sm-4 col-sm-offset-4 well"><%= yield :profile %></div>
      </div>
    <% elsif content_for? :messenger %>
    <div id="page-content" class="flexcol">
      <div class="row flexrow">
        <div class="col-sm-3 flexrow" >
          <div id="dash-nav" class="flexcol well">
            <%= render "layouts/dash_nav_messenger" %>
          </div>
        </div>
        <div class="col-sm-9 flexrow">
          <div class="flexcol well">
            <%= render 'layouts/notices' %>
            <div id="dash-content"><%= yield :messenger %></div>
          </div>
        </div>
      </div>
    </div>
    <% else %>
    <div id="page-content" class="flexcol">
      <div class="row flexrow">
        <div class="col-sm-3 flexrow" >
          <div id="dash-nav" class="flexcol well">
            <%= render "layouts/dash_nav" %>
          </div>
        </div>
        <div class="col-sm-9 flexrow">
          <div class="flexcol well">
            <%= render 'layouts/notices' %>
            <div id="dash-content"><%= yield %></div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% else %>
    <div id="page-content"><%= yield %></div>
    <% end %>
  </div>
  <%= render 'layouts/footer' %>
<% end %>

</body>
</html>